name: Create and publish a Docker image for nkd test

on:
  push:
    branches: ['test']

env:
  REGISTRY: docker.io
  IMAGE_NAME: nkdtechteam/user-app-backend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy in Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NKD_SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.NKD_SERVER_PEM }}
          script: |
            pwd
            cd /home/ubuntu/dev
            docker compose -f docker-compose-nkd.yml pull
            docker compose -f docker-compose-nkd.yml up -d
            docker image prune -af