# We can use this after every thing sorted out

# version: '3.8'

# services:
#   mysql:
#     image: mysql
#     container_name: mysql-local
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: nkd
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     ports:
#       - "3306:3306"
